# packages/grw-smoothing-models/pyproject.toml
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "grw-smoothing-models"
version = "0.1.0"
description = "GRW-smoothing"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "grw-smoothing",
    "wandb",
    "torch>=2.3",
    "torchvision",
    "scikit-learn",
    "plotly",
    "movinet-pytorch @ git+https://github.com/gilgoldm/MoViNet-pytorch",
    "fvcore",
    "einops",
    "av==12.0.0",
    "pyvista",
    "kaleido",
    "more-itertools>=10.8.0",
]
